import streamlit.components.v1 as components
import streamlit as st


def carrega_cartilha():
    st.markdown('<div style="position: relative; width: 100%; height: 0; padding-top: 141.4286%; padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden; border-radius: 8px; will-change: transform;">  <iframe loading="lazy" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAFj4OPB9Mg&#x2F;view?embed" allowfullscreen="allowfullscreen" allow="fullscreen">  </iframe></div><a href="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAFj4OPB9Mg&#x2F;view?utm_content=DAFj4OPB9Mg&amp;utm_campaign=designshare&amp;utm_medium=embeds&amp;utm_source=link" target="_blank"</a> ',True)

    st.header('Referências Utilizadas')
    with st.expander('Referências Utilizadas'):    
        st.write('AGÊNCIA BRASIL (2020) “Pesquisa mostra exclusão de idosos do mundo digital e da escrita”,https://agenciabrasil.ebc.com.br/geral/noticia/2020-08/pesquisa-mostra-exclusao-de-idosos-do-mundo-digital-e-da-escrita, Agosto.')
        st.write('AGÊNCIA BRASIL (2021) “Estudo mostra que pandemia intensificou uso das tecnologias digitais”, https://agenciabrasil.ebc.com.br/geral/noticia/2021-11/estudo-mostra-que-pandemia-intensificou-uso-das-tecnologias-digitais, Novembro.')
        st.write('BBC NEWS BRASIL (2021) “Nativos digitais não sabem buscar conhecimento na internet, diz OCDE”, https://www.bbc.com/portuguese/geral-57286155, Maio.')
        st.write('BRASIL ESCOLA (?) "Cyberbullying", https://brasilescola.uol.com.br/sociologia/cyberbullying.htm')
        st.write('CERT (?) “Cartilha de Segurança Para a Internet”, https://cartilha.cert.br/fasciculos/.')
        st.write('CGIBR (2012) “Cartilha de Segurança para a Internet”, https://www.cgi.br/publicacao/cartilha-de-seguranca-para-internet/.')
        st.write('CYBERTECH BRASIL (2022) “Cartilha CyberTech Brasil de conscientização em segurança”, https://cybertechbr.org/baixe-ja-nossa-cartilha-cybertech-brasil-de-conscientizacao-em-seguranca/')
        st.write('DANRESA (2023) "Os Riscos do Uso de WiFi em Aeroportos e Como se Proteger", https://www.danresa.com.br/danresa-portal/ciberseguranca/os-riscos-do-uso-de-wifi-em-aeroportos-e-como-se-proteger/, Maio.')
        st.write('ESTADO DE MINAS (2023) “Discord na mira: coação, chantagem e violência entre jovens”, https://www.em.com.br/app/noticia/tecnologia/2023/06/28/interna_tecnologia,1513306/discord-na-mira-coacao-chantagem-e-violencia-entre-jovens.shtml, Junho.')
        st.write('FEBRABAN (2021) “Medo, ganância e desconhecimento são iscas para golpes digitais, alertam especialistas”, https://febrabantech.febraban.org.br/videos/medo-ganancia-e-desconhecimento-sao-iscas-para-golpes-digitais-alertam-especialistas, Fevereiro.')
        st.write('Ferreira T. R. S. C., Deslandes, S. F. (2018). “Cyberbullying: conceituações, dinâmicas, personagens e implicações à saúde”, https://www.scielosp.org/article/csc/2018.v23n10/3369-3379/ .Outubro')
        st.write('FIA (2023) "Cyberbullying: o que é, consequências e dados no Brasil", https://fia.com.br/blog/cyberbullying/, Janeiro.')    
        st.write('FORBES (2020) "Cibersegurança: entenda os perigos do ambiente digital", https://forbes.com.br/forbes-tech/2020/11/ciberseguranca-entenda-os-perigos-do-ambiente-digital/, Novembro.')
        st.write('G1 (2016) "Software Livre: vale a pena ser substituído por programas pagos?", https://g1.globo.com/tecnologia/blog/tira-duvidas-de-tecnologia/post/software-livre-vale-pena-ser-substituido-por-programas-pagos.html, Novembro.')
        st.write('G1 (2022) “Tentativas de golpes por meios digitais cresceram 20% no segundo trimestre deste ano no Brasil”, https://g1.globo.com/tecnologia/noticia/2022/10/11/tentativas-de-golpes-por-meios-digitais-cresceram-20percent-no-segundo-trimestre-deste-ano-no-brasil.ghtml, Outubro.')
        st.write('G1 (2023) "Ex-BBB recebe ataques nas redes sociais após fazer apelo para encontrar mãe desaparecida; caso foi registrado na polícia há 2 meses", https://g1.globo.com/ba/bahia/noticia/2023/06/26/ex-bbb-recebe-ataques-nas-redes-sociais-apos-fazer-apelo-para-encontrar-mae-desaparecida-caso-foi-registrado-na-policia-ha-2-meses.ghtml, Junho.')
        st.write('GOVERNO DO BRASIL (2022) "90\%\dos lares brasileiros já tem acesso à internet no Brasil, aponta pesquisa", https://www.gov.br/casacivil/pt-br/assuntos/noticias/2022/setembro/90-dos-lares-brasileiros-ja-tem-acesso-a-internet-no-brasil-aponta-pesquisa, Outubro.')
        st.write('KAPERSKY (?) "Centro de recursos", https://www.kaspersky.com.br/resource-center')
        st.write('KAPERSKY (?) "Como evitar riscos à segurança em redes Wi-Fi públicas", https://www.kaspersky.com.br/resource-center/preemptive-safety/public-wifi-risks')
        st.write('KAPERSKY (?) "Bullying virtual: O crime virtual do século", https://www.kaspersky.com.br/resource-center/preemptive-safety/cyberbullying-and-cybercrime/')
        st.write('MINISTÉRIO DA EDUCAÇÃO (2023) “ESCOLA SEGURA - Como lidar com conteúdos de violência online e conversar com crianças e jovens sobre o tema”, https://www.gov.br/mec/pt-br/assuntos/noticias/mec-lanca-cartilha-para-enfrentamento-a-violencia-on-line.')
        st.write('MINISTERIO PÚBLICO DFT (2015) “Cartilha Orientativa Ética e Segurança Digital”, https://www.mpdft.mp.br/portal/pdf/imprensa/cartilhas/Cartilha_Orientativa_Etica_Seguranca_Digital_MPDFT.pdf.')
        st.write('MICROSOFT (2022) "Sete coisas que você deve saber para se proteger ao acessar redes Wi-Fi públicas", https://news.microsoft.com/pt-br/sete-coisas-que-voce-deve-saber-para-se-proteger-ao-acessar-redes-wi-fi-publicas/')
        st.write('OAB-SP (2023) “Segurança da Informação - Cartilha de Boas Práticas para Advogados”, https://jornaldaadvocacia.oabsp.org.br/wp-content/uploads/2023/04/cartilha-boas-praticas-virtuais-oab-sp.pdf')
        st.write('OLHAR DIGITAL (2022) "FBI alerta turistas sobre o uso de redes Wi-Fi públicas", https://olhardigital.com.br/2019/12/18/seguranca/fbi-alerta-turistas-sobre-o-uso-de-redes-wi-fi-publicas/')
        st.write('OLHAR DIGITAL (2022) "Quais são os sinais de um perfil falso nas redes sociais?", https://olhardigital.com.br/2022/04/29/tira-duvidas/sinais-perfil-falso-redes-sociais/, Abril.')
        st.write('PLANALTO (2014) “Cartilha da Segurança - Simples Atitudes que Podem Evitar Grandes Problemas”, http://www4.planalto.gov.br/cgd/assuntos/publicacoes/campanha-de-sensibilizacao-em-sic-2014/cartilha-de-seguranca-da-informacao.pdf.')
        st.write('SAFERNET (2015) “Diálogo Virtual 2.0: Preocupado com o que acontece na Internet? Quer Conversar?”, https://new.safernet.org.br/sites/default/files/content_files/Di%C3%A1logo_Virtual_Low_Web_SN_Unicef_PFDC_CGI.pdf.')
        st.write('SAFERNET (?) “Canal de Denúncia”, https://new.safernet.org.br/denuncie')
        st.write('SAFERNET (?) “O que é cyberbullying?” https://new.safernet.org.br/content/o-que-e-ciberbullying')
        st.write('SAFERNET (?) “Cyberbullying: saiba como identificar e como agir”. https://new.safernet.org.br/content/ciberbullying-saiba-como-identificar-e-como-agir ')
        st.write('SAFERNET (?) “Estou enfrentando um problema de cyberbullying. Devo denunciar?” https://new.safernet.org.br/content/estou-enfrentando-um-problema-de-cyberbullying-devo-denunciar')
        st.write('Schreiber, F. C. C., Antunes, M. C. (2015). “Cyberbullying: do virtual ao psicológico”, http://pepsic.bvsalud.org/scielo.php?script=sci_arttext&pid=S1415-711X2015000100008 . Janeiro.')
        st.write('TECMUNDO (2013) "Quais os riscos de usar um WiFi público?", https://www.tecmundo.com.br/wi-fi/39348-quais-os-riscos-de-usar-um-wifi-publico-.htm, Maio.')
        st.write('TILT (2022) "Descubra se um perfil é fake no Instagram, Facebook, WhatsApp e TikTok", https://www.uol.com.br/tilt/noticias/redacao/2022/04/26/como-saber-se-perfil-e-fake-no-instagram-facebook-whatsapp-e-tiktok.htm, Abril.')
        st.write('TWIST (2020) "O que são bots e como agem?", https://www.twist.systems/pt-br/blog/2020/03/26/o-que-sao-bots-como-agem/')
        st.write('UFRGS (2021) “Cartilha de Segurança da Informação”, https://www.ufrgs.br/cpd/wp-content/uploads/2021/05/CartilhaSegurancaInformacao.pdf')
        st.write('UNICEF (2019)	“Pesquisa do UNICEF: Mais de um terço dos jovens em 30 países relatam ser vítimas de bullying online”	https://www.unicef.org/brazil/comunicados-de-imprensa/mais-de-um-terco-dos-jovens-em-30-paises-relatam-ser-vitimas-bullying-online')
        st.write('WORLD HEALTH ORGANIZATION (2020) “WHO Director-Generals opening remarks at the media briefing on COVID-19 - 11 March 2020”, https://www.who.int/director-general/speeches/detail/who-director-general-s-opening-remarks-at-the-media-briefing-on-covid-19---11-march-2020 , Março.')